# Generated by Django 4.0.3 on 2022-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('user_account_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registered Users',
                'verbose_name_plural': 'Registered Users',
            },
        ),
    ]
