# Generated by Django 4.0.3 on 2022-04-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_alter_users_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
