# Generated by Django 4.0.3 on 2022-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='uploadedImages')),
                ('image_name', models.CharField(max_length=100)),
                ('image_description', models.CharField(max_length=100)),
                ('image_upload_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uploaded Images',
                'verbose_name_plural': 'Uploaded Images',
            },
        ),
    ]
