# Generated by Django 4.0.3 on 2022-03-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimages',
            old_name='image file',
            new_name='image_file',
        ),
    ]
